export const YCS_DECK = [
  { name: "Sinful Spoils of the White Forest" },
  { name: "Infinite Impermanence" },
  { name: "Infinite Impermanence" },
  { name: "Infinite Impermanence" },
  { name: "Ash Blossom & Joyous Spring" },
  { name: "Ash Blossom & Joyous Spring" },
  { name: "Ash Blossom & Joyous Spring" },
  { name: "Called by the Grave" },
  { name: "Rucia of the White Forest" },
  { name: "Triple Tactics Talent" },
  { name: "Diabell Nueva" },
  { name: "Diablezze nueva" },
  { name: "Lacrima the Crimson Tears" },
  { name: "Elzette, Azamina of the White Forest" },
  { name: "Azamina Aphes" },
  { name: "Mulcharmy Fuwalos" },
  { name: "Mulcharmy Fuwalos" },
  { name: "Mulcharmy Fuwalos" },
  { name: "Whitches of the White Forest" },
  { name: "Whitches of the White Forest" },
  { name: "Fiendsmith Engraver" },
  { name: "Fiendsmith Engraver" },
  { name: "Fiendsmith Engraver" },
  { name: "Elzette of the White Forest" },
  { name: "Elzette of the White Forest" },
  { name: "Elzette of the White Forest" },
  { name: "Deception of the Sinful Spoils" },
  { name: "Diabellstar the Black Witch" },
  { name: "Diabellstar the Black Witch" },
  { name: "WANTED: Seeker of Sinful Spoils" },
  { name: "WANTED: Seeker of Sinful Spoils" },
  { name: "WANTED: Seeker of Sinful Spoils" },
  { name: "The Hallowed Azamina" },
  { name: "Fabled Lurrie" },
  { name: "Silvy of the White Forest" },
  { name: "Silvy of the White Forest" },
  { name: "Silvy of the White Forest" },
  { name: "Fiendsmith's Tract" },
  { name: "Tales of the White Forest" },
  { name: "Fiendsmith in Paradise" },
];
